# Generated by Django 3.1.4 on 2020-12-13 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20201212_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBox',
            new_name='Message',
        ),
    ]
