version: "3.7"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:12"
    restart: "always"
    environment:
      POSTGRES_DB: "chatdb"
      POSTGRES_USER: "chatuser"
      POSTGRES_PASSWORD: "chatpassword"
    ports: [ "5432:5432" ]
    volumes: [ "~/data/ChatApp/pgdata:/var/lib/postgresql/data/" ]
  django:
    container_name: "django"
    build: .
    restart: "always"
    environment:
      DATABASE: "chatdb"
      USERNAME: "chatuser"
      PASSWORD: "chatpassword"
      HOST: "postgres"
      PORT: "5432"
    ports: [ "80:8000" ]
    volumes: [ ".:/code" ]
    depends_on: [ "postgres" ]
